"""init migration

Revision ID: e8fb749b0ed8
Revises: 
Create Date: 2026-10-03 10:40:30.558915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fb749b0ed8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='user_role_enum'), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('surname', sa.String(length=16), nullable=False),
    sa.Column('patronymic', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chats',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_type', sa.Enum('private', 'group', name='chat_type_enum'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_chats',
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('chat_name', sa.String(length=16), nullable=False),
    sa.Column('chat_desc', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_chat_id_created_at_id', 'messages', ['chat_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('private_chats',
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('user_1_id', sa.Uuid(), nullable=True),
    sa.Column('user_2_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('user_1_id < user_2_id', name='ck_private_chats_users_ordered'),
    sa.CheckConstraint('user_1_id <> user_2_id', name='ck_private_chats_users_different'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_1_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_2_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('chat_id'),
    sa.UniqueConstraint('user_1_id', 'user_2_id', name='uq_private_chats_user_pair')
    )
    op.create_index(op.f('ix_private_chats_user_1_id'), 'private_chats', ['user_1_id'], unique=False)
    op.create_index(op.f('ix_private_chats_user_2_id'), 'private_chats', ['user_2_id'], unique=False)
    op.create_table('group_chat_members',
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('member', 'owner', name='chat_member_role_enum'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['group_chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_index(op.f('ix_group_chat_members_user_id'), 'group_chat_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_chat_members_user_id'), table_name='group_chat_members')
    op.drop_table('group_chat_members')
    op.drop_index(op.f('ix_private_chats_user_2_id'), table_name='private_chats')
    op.drop_index(op.f('ix_private_chats_user_1_id'), table_name='private_chats')
    op.drop_table('private_chats')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_index('ix_messages_chat_id_created_at_id', table_name='messages')
    op.drop_table('messages')
    op.drop_table('group_chats')
    op.drop_table('chats')
    op.drop_table('users')
    # ### end Alembic commands ###
